[package]
name = "wson"
version = "0.1.0"
edition = "2021"
authors = ["LunaStev <lunastev@gurmstudis.com>"]
description = "WSON data serialization parser "
license = "MPL-2.0"
repository = "https://github.com/Wave/wson-rust"
publish = true

[lib]
name = "wson"
path = "src/lib.rs"
